### ISSUE TITLE
Firefox extension no more shows 256kbps M4A links on youtube

### ISSUE THREAD

**Issue by goldencut** [inbasic/iaextractor#102]
Downloaded 256kbps M4A from https://www.youtube.com/watch?v=Z5QTApU2_jc, saw that it was left as DASH-file so upgraded the add-on and went to re-download the file but there's no link to download 256kbps anymore, only 128.

**Comment by inbasic** [comment]
>  it was left as DASH-file

Seems like you don't have FFmpeg or the extension cannot find it. Try to download it manually and then from the settings page, point the extension to use the executable.
