### ISSUE TITLE
When downloading 4k 60fps VP9 webm video, YouTube Video and Audio Downloader downloads AAC (in M4A container) instead of Opus audio

### ISSUE THREAD

**Issue by aufkrawall** [inbasic/iaextractor#103]
In the options, i chose to let it download Opus audio if available.
This generally works, but not with this 4k 60fps VP9 webm video:
https://www.youtube.com/watch?v=aqz-KE-bpKQ
When I download the 30fps video, it downloads Opus audio. But with 60fps, it chooses AAC. It should also choose Opus for the 60fps video since I enabled the option to download Opus when available.

**Comment by aufkrawall** [comment]
Hello,
this issue still exists. Would be neat if it could be fixed.
Thanks.

**Comment by inbasic** [comment]
Thanks for the report. It is now fixed on the beta channel.

https://github.com/inbasic/iaextractor/blob/beta/src/iaextractor.xpi?raw=true

Download the XPI file and drop it into your Firefox browser.

**Comment by aufkrawall** [comment]
I can confirm it's fixed, thank you.
