### ISSUE TITLE
Unable to download age-restricted YouTube videos

### ISSUE THREAD

**Issue by ChodaBoy** [inbasic/iaextractor#104]
Even though I am signed into YouTube and can play the video, https://www.youtube.com/watch?v=k3IlHBBGCIw, when I attempt to download it I receive the following error:
>YouTube Video and Audio Downloader
>Error: Cannot detect url_encoded_fmt_stream_map or adaptive_fmts in the response HTML file., info server failed with: Sign+in+to+confirm+your+age

![ytdownloaderrorsignin](https://cloud.githubusercontent.com/assets/2310708/10526227/302d30dc-734f-11e5-88cd-2b39ff1961b2.png)
I have checked the following:
* I am signed into YouTube and can play the video
* I am NOT using a Private Window
* Options - Privacy - History is set to "Remember History"
* No ad blocking extension is Enabled
* No https enforcing extension is Enabled

Any ideas on how to resolve this?

**Comment by BrianHath777** [comment]
works fine for me with Firefox 40.0.3 (Macintosh) + YouTube Audio/Video DL'r 0.4.4.1.1-signed


--------------------------------------------
On Thu, 10/15/15, ChodaBoy <notifications@github.com> wrote:

 Subject: [iaextractor] Unable to download age-restricted YouTube videos (#104)
 To: "inbasic/iaextractor" <iaextractor@noreply.github.com>
 Date: Thursday, October 15, 2015, 4:14 PM
 
 Even though I am signed into
 YouTube and can play the video, https://www.youtube.com/watch?v=k3IlHBBGCIw,
 when I attempt to download it I receive the following
 error:
 
 
 YouTube Video and Audio Downloader
 
 Error: Cannot detect url_encoded_fmt_stream_map or
 adaptive_fmts in the response HTML file., info server failed
 with: Sign+in+to+confirm+your+age
 
 
 
 
 I have checked the following:
 
 
 I am signed into YouTube and can play the video
 I am NOT using a Private Window
 Options - Privacy - History is set to "Remember
 History"
 No ad blocking extension is Enabled
 No https enforcing extension is Enabled
 
 
 Any ideas on how to resolve this?
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by ChodaBoy** [comment]
I have Firefox 40.0.1 with YouTube Video and Audio Downloader 0.4.5

I had intended to include this in my original post.

**Comment by BrianHath777** [comment]
use a back-rev - the latest version of YouTube downloader has restrictive bugs - can't see 256K audio, for instance

**Comment by szeiger** [comment]
I have the same problem. I tried both 0.4.5 and 0.4.4.11. It still fails the same way when run from a completely new profile (nothing but this extension installed, all settings default)

**Comment by ekaris** [comment]
Same problem here using this video: https://www.youtube.com/watch?v=nUWNBPVRjTw&list=PLpwyzkZha0Z6qbceVlKbD0B6SrYaWpZVG&index=2

**Comment by ekaris** [comment]
@inbasic can you reproduce the bug?

**Comment by inbasic** [comment]
No! Are you sure you are not logged-in in the provide mode?
![screen shot 2016-02-16 at 12 40 32](https://cloud.githubusercontent.com/assets/351062/13071745/a9486222-d4aa-11e5-98f9-c9f762360132.png)

**Comment by ekaris** [comment]
Yes, I’m logged in and I even disabled all extension except this one and the problem remains, im using ubuntu 64 bits and firefox 44.0.2

**Comment by inbasic** [comment]
Can you try on a clean profile?
http://blog.add0n.com/2016/02/11/configure-proxy-settings-in-firefox.html

**Comment by ekaris** [comment]
@inbasic Yes it works on a clean profile, now we have to nail the issue, any ideas?

**Comment by BrianHath777** [comment]
I have a very "unclean" profile and it works fine on my FF.  You have some sort of corruption OR a conflict with some other app / ext.

**Comment by inbasic** [comment]
Maybe you are logged-in in a private browsing mode?

**Comment by ekaris** [comment]
No private browser

**Comment by inbasic** [comment]
Can you guys try the latest built?
https://github.com/inbasic/iaextractor/blob/beta/builds/feca4b87-3be4-43da-a1b1-137c24220968@jetpack-0.5.0b4.xpi?raw=true and let me know if it is fixed or not

**Comment by inbasic** [comment]
Please re-open if you still have the issue.

**Comment by ekaris** [comment]
Works for me

**Comment by ekaris** [comment]
It doesn't work in private browser mode

**Comment by inbasic** [comment]
YVAD uses same context as the normal mode. So when you are on the private mode, it is like you are not logged-in from YVAD side and hence downloading age-restricted videos are forbidden.
