### ISSUE TITLE
Couldn't find the temp download folder

### ISSUE THREAD

**Issue by gundamftw** [inbasic/iaextractor#105]
I was using the firefox plugin and tried to download a youtube video to E drive, and C drive went out of space while in the muxing stage.  I need an option to locate that temp folder because the files from the failed attempt is taking up the space in my C drive.  I tried Windows disk cleanup but there were not there.

**Comment by gundamftw** [comment]
Okay, the files from the failed attempt shows up correctly in the Windows temp folder now, my problem has been solved.

**Comment by inbasic** [comment]
Take a look at the "special locations" section of https://developer.mozilla.org/en-US/Add-ons/Code_snippets/File_I_O#Storing_nsILocalFile_in_preferences
