### ISSUE TITLE
Firefox WebExtentions

### ISSUE THREAD

**Issue by jeffbeu** [inbasic/iaextractor#107]
Hello,

Some background:
I made some changes iaextractor to allow Audio to be preferred in regards to the one-click mode. I am considering doing a proper integration and pushing the changes but hesitant to do so because of a concern this project will be discontinued due to Firefox API changes, thus wasting my time.

Would I be wasting my time?

Thanks for the great work!

**Comment by inbasic** [comment]
Jeff there is no guarantee, we will try to keep the project going as far as we can. That's it!

**Comment by jeffbeu** [comment]
Thanks for the response.

To be upfront I thought the project was already dead given the commit history but it appears I was wrong given the Mozilla addon update history. 

So would it be safe to assume this project is not open or is it now hosted elsewhere?

**Comment by inbasic** [comment]
well, no body is actively working on this project anymore. But I still keep maintaining it once per while. I just pushed the latest changes to the beta channel, so if you want to play around, use this channel as the reference.
https://github.com/inbasic/iaextractor/commits/beta

**Comment by inbasic** [comment]
Please reopen if you intend to contribute.

**Comment by jeffbeu** [comment]
I clicked some buttons and know you have a pull request from me, It wasn't my intention but I will go with the flow.
