### ISSUE TITLE
Null issue

### ISSUE THREAD

**Issue by CharlieUtter** [inbasic/iaextractor#108]
I was able to download videos up until about 2 weeks ago,now when I open the app, I get a list of video files but they all have "null" next to them rather than the size of the file.  When I try to download one of them it does no work.  Will there be an update to this file soon?

Thanks!

Charlie Utter

**Comment by Xiron805** [comment]
I have the same problem and am looking for a solution

cheers

**Comment by inbasic** [comment]
It will be fixed on version 0.4.6

Thanks for the report.
