### ISSUE TITLE
Check whether ffmpeg exists + provide form field for ffmpeg symlink path

### ISSUE THREAD

**Issue by jekuno** [inbasic/iaextractor#111]
I had the same issue as described in #36.

As homebrew frequently installs updates of ffmpeg the path to ffmpeg was broken many times.
However `iaextractor` silently ignores that ffmpeg can't be located any more and downloads the video file nevertheless and produces a video without audio.

If the user chooses a conversion option which requires ffmpeg it would be good if  `iaextractor` checks whether ffmpeg exists _before_ downloading a video.

Also it would be nice if there would be a form field to enter the path to the ffmpeg symlink manually (additionally to the file chooser for chosing the ffmpeg binary) so that users don't need to edit the about:config manually.

If it's not possible to add a form field at least a hint in the documentation or in the preferences panel would be good how to workaround this issue (as described in #36).

**Comment by inbasic** [comment]
Thanks for the suggestion. In the latest dev version there is a new field in the settings page to allow expert users to insert the path manually.
https://github.com/inbasic/iaextractor/blob/beta/src/iaextractor.xpi?raw=true

**Comment by jekuno** [comment]
Thanks for resolving this so fast :+1:
