### ISSUE TITLE
files for ffmpeg combiner

### ISSUE THREAD

**Issue by dans3** [inbasic/iaextractor#115]
I use custom download folder. Input and output files in ffmpeg command line (in Process Explorer) are located in windows temp folder. There are 3 unnecessary disk operations (copying to temp and back).

**Comment by inbasic** [comment]
This is necessary as ffmpeg is not working well if file-name contains characters outside utf-8

**Comment by inbasic** [comment]
We are not copying files to the temp directory anymore on the latest version

https://github.com/inbasic/iaextractor/blob/beta/builds/feca4b87-3be4-43da-a1b1-137c24220968@jetpack-0.5.2b1.xpi?raw=true
