### ISSUE TITLE
256K Audio gone again - version 0.4.8

### ISSUE THREAD

**Issue by BrianHath777** [inbasic/iaextractor#121]
160K Opus and 128K M4a is the highest audio bitrate that is populating now. Damn them. Damn their eyes. Curse their hobbit holes! (please fix)

**Comment by BrianHath777** [comment]
^ has YT themselves "plugged" this so the extension must be adjusted again?

**Comment by inbasic** [comment]
Do you get a better bit-rate from another extension?

**Comment by BrianHath777** [comment]
Don't understand the question.  ??

**Comment by inbasic** [comment]
So can you confirm better bit-rates are available but YVAD cannot detect them?

**Comment by BrianHath777** [comment]
YES!   Several old files that used to list 256 don't now - highest is 160 OPUS .webm files now - 128 m4a's.  This has happened before and was fixed.

--------------------------------------------
On Sat, 2/27/16, InBasic <notifications@github.com> wrote:
 
 So can you confirm better
 bit-rates are available but YVAD cannot detect them?

**Comment by BrianHath777** [comment]
SeaMonkey sees the 192K mp3 audio files via the Best Video Downloader 2 extension for SeaMonkey (it can't go up to 256K files) - whenever that rate is seen (at least up till now) that meant a 256K m4a file was available in Firefox via the YouTube Video and Audio Downloader extension ...... just fyi.

**Comment by mzso** [comment]
[**@BrianHath777**](https://github.com/BrianHath777) commented on [2016. márc. 4. 04:33 CET](https://github.com/inbasic/iaextractor/issues/121#issuecomment-192081712 "2016-03-04T03:33:52Z - Replied by Github Comment Enhancer"):
> <div class="email-fragment">SeaMonkey sees the 192K mp3 audio files via the Best Video Downloader 2 extension for SeaMonkey (it can't go up to 256K files) - whenever that rate is seen (at least up till now) that meant a 256K m4a file was available in Firefox via the YouTube Video and Audio Downloader extension ...... just fyi.</div>

There's no such thing. Youtube doesn't provide mp3 files. It must convert it from another format.

**Comment by inbasic** [comment]
256K doesn't seem to be available anymore. Please re-open if you can get it by another extension.
