### ISSUE TITLE
Best audio (opus160) not chosen, Downloaded audio (aac128) not muxed.

### ISSUE THREAD

**Issue by mzso** [inbasic/iaextractor#125]
Hi!

I noticed this today. Contrary to the information provided in the configuration page this addon downloaded the AAC 126 kbps stream instead of the opus 160kbps one. But when the download finished it didn't mux it with the video.
On the third attempt I noticed a  YVAD error message showing that the encoder exited with -1 as a status.

I've testing with these videos downloading the UHD60p streams:
https://www.youtube.com/watch?v=Z6lYqgWAmrg
https://www.youtube.com/watch?v=AuaLl2pII2Q
https://www.youtube.com/watch?v=B7wkzmZ4GBw

Ffmpeg is properly set up. I tried it with a different stream.

PS:
https://www.youtube.com/watch?v=ly4vJanKNZg - This video doesn't show up as high fps, guessing because it's 50 fps instead of 60.

**Comment by inbasic** [comment]
> Contrary to the information provided in the configuration page this addon downloaded the AAC 126 kbps stream instead of the opus 160kbps one

For what video-only item?

**Comment by inbasic** [comment]
> https://www.youtube.com/watch?v=ly4vJanKNZg - This video doesn't show up as high fps, guessing because it's 50 fps instead of 60.

50 fps is supported now; https://github.com/inbasic/iaextractor/commit/f173583657ccba82342aed2ac16bc5c7495bab68

**Comment by mzso** [comment]
[**@inbasic**](https://github.com/inbasic) commented on [2016. ápr. 2. 10:18 CEST](https://github.com/inbasic/iaextractor/issues/125#issuecomment-204671378 "2016-04-02T08:18:37Z - Replied by Github Comment Enhancer"):
> > Contrary to the information provided in the configuration page this addon downloaded the AAC 126 kbps stream instead of the opus 160kbps one
> 
> For what video-only item?

Yes. There's only one kind of UHD 60fps stream it's a VP9 stream. It's rather unexpected that the addon downloaded the AAC file for a VP9 video. It apparently only happens to this stream.

Apart from this. Since youtube removed the 256 kbit AAC stream, the 160kbps OPUS stream became the best quality audio stream. So in my opinion it shoud be downloaded even for AVC streams, at least when "Always download the highest audio quality available in the batch-mode:" is checked.
A little complication that neither mp4 or webm supports this combination. So mkv needs to be used.

**Comment by BrianHath777** [comment]
It's not certain that YouTube 'removed' the 256 bit stream - only that the present version of this Add-On can no longer see it.  That happened before in 2015, but was later 'fixed.'

**Comment by mzso** [comment]
I'm quite sure they did. No tools see it anymore, and no-one found a way to get it back.

**Comment by inbasic** [comment]
@mzso 

> It's rather unexpected that the addon downloaded the AAC file for a VP9 video. It apparently only happens to this stream.

If on https://www.youtube.com/watch?v=Z6lYqgWAmrg "WEBM 2160p video-only - 700 MB" is selected, YVAD grabs "WEBM Audio-only - OPUS 160K - 2.8 MB" for audio. Do you get another combination?

**Comment by mzso** [comment]
0.4.8 shows the behavior i described. (Downloading AAC128 and failing to merge).
0.5.0b1 starts downloading the proper audio file. (I didn't wait for them to finish, because I don't have much bandwitdth)

**Comment by inbasic** [comment]
Perfect! Thanks for the report.
