### ISSUE TITLE
Add support for using FFMPEG on Linux

### ISSUE THREAD

**Issue by ekaris** [inbasic/iaextractor#126]
Add support for using FFMPEG conversion on Linux

**Comment by ekaris** [comment]
@inbasic This should be easy to add, the commands are the same and ffpmeg is just a click from installation on most Linux systems, if you need help I can be of assistance

**Comment by inbasic** [comment]
As far as I know FFMpeg is supported under Debian based Linux distributions. I have never tried other distributions though. Can you be more specific of the issue?

**Comment by ekaris** [comment]
It is supported on most if not all Linux distros, all we have to do on debian, ubuntu and derivatives is call the command line and enter sudo apt-get install ffmpeg, and it installs ffmpeg in /usr/bin/
You could set it to search in that directory automatically and if not found provide a dialog box to choose the folder.

**Comment by ekaris** [comment]
The issue is that YouTube Video and Audio Downloader only supports ffmpeg .exe

**Comment by inbasic** [comment]
> https://github.com/inbasic/iaextractor/commit/2a21e43264a9a6a5bda4b5247900f197d567d19b

That's not true. YVAD does support Linux and Darwin; https://github.com/inbasic/iaextractor/blob/beta/src/lib/external.js#L56:L69 In fact the extension checks the PATH enviroment variable to find FFmpeg. If it is not found, YVAD offers pre-executable download of FFmpeg.

**Comment by ekaris** [comment]
Ok, you should remove the "...(.exe)" from the addon as it confuses people into thinking it is windows only

**Comment by inbasic** [comment]
Since a considerable amount of users are on Windows machines that helps them to find the right executable. In the next release we will have a better options window though. Hopefully it prevents these sort of confusions.

![screen shot 2016-04-04 at 12 47 59](https://cloud.githubusercontent.com/assets/351062/14241956/cba51840-fa63-11e5-85fa-f784d7f4898c.png)
