### ISSUE TITLE
What's the best file to simply have the audio file and burn the music on a CD?

### ISSUE THREAD

**Issue by MonkeysLP** [inbasic/iaextractor#127]
I don't want any video or anything. Just downloading songs for a music CD.

**Comment by inbasic** [comment]
I would say download audio-only items. Let the extension extract the original audio files (assuming you already have FFmpeg installed). When you are done with your downloads, use https://addons.mozilla.org/en-US/firefox/addon/media-converter-and-muxer/. Open the UI and drag the whole album and convert them to MP3 format.
