### ISSUE TITLE
1080P is the only format I can download

### ISSUE THREAD

**Issue by solarduck001** [inbasic/iaextractor#131]
I don't know what happen but the GUI changed and no matter what format I want I can only download 1080P, why is that?

**Comment by inbasic** [comment]
Do you mean the "Quick Download" button gets the 1080p?

**Comment by solarduck001** [comment]
yes
 
-----Original Message-----

**Comment by inbasic** [comment]
Go to about:addons and find options window of the extension. In the "Quick Download" tab what is the preferred format and quality.

**Comment by solarduck001** [comment]
1080p is listed but I change that to 720p and that setting isn't stickey..it reverts back to 1080p
 
-----Original Message-----

**Comment by inbasic** [comment]
After 720 is selected you need to press the OK button. Have you done this?

**Comment by solarduck001** [comment]
yes
 
-----Original Message-----

**Comment by inbasic** [comment]
Can you confirm this on a clean profile; http://blog.add0n.com/2016/01/30/how-to-use-firefox-profile-manager.html
