### ISSUE TITLE
Sometimes streams are still not merged.

### ISSUE THREAD

**Issue by mzso** [inbasic/iaextractor#132]
I downloaded the 1080p AVC streams for these videos:
https://www.youtube.com/watch?v=yLC4qsUvkio
https://www.youtube.com/watch?v=15QHWsgtES0

The video/audio files weren't merged.

**Comment by inbasic** [comment]
Can you merge them manually using the command line FFmpeg? Are you sure your FFmpeg is up-to-date?

**Comment by mzso** [comment]
I've had the same command line for ages. and it always worked. FFmpeg didn't change anything command line wise.

Also different resolutions for the same video (such as "mp4 240p", "mp4 360p") works.

**Comment by mzso** [comment]
I just got an ffmpeg exited error while the video stream was still downloading and got nothing when it finished downloading.

**Comment by inbasic** [comment]
> FFmpeg didn't change anything command line wise.
No for sure the commend line options are the same. Just newer versions have better merging supports.

> I just got an ffmpeg exited error while the video stream was still downloading and got nothing when it finished downloading.

That's weird! Anyway to reproduce this.

**Comment by inbasic** [comment]
Btw, the DASH files are still available right? YVAD is supposed to delete the DASH files if merging is successful

**Comment by mzso** [comment]
Yes, they're not deleted.

**Comment by TheMainDude** [comment]
I have the same problem. Not on every video but happens often.
When it doesnt work I am left with a video file (no sound) and the sound file. Is it possible to merge them ?

**Comment by inbasic** [comment]
@TheMainDude try getting a fresh FFmpeg from https://www.ffmpeg.org/download.html and point the extension to use the new FFmpeg.

**Comment by mzso** [comment]
In response to: https://github.com/inbasic/iaextractor/issues/123#issuecomment-213744153

> @mzso please try https://github.com/inbasic/iaextractor/blob/beta/builds/feca4b87-3be4-43da-a1b1-137c24220968@jetpack-0.5.1b3.xpi?raw=true and let me know if the extension still fails to delete the tmp folder/file
> 
>     I don't understand why this addon puts files there pointlessly
> 
> FFmpeg is not good at handling non Unicode chars. That's the only reason.
> 
> 

You mean non-ASCII characters, right? I'm not sure non-unicode characters even exist.
Anyway my experience is entirely the opposite. It handles everything I throw at it from cyrillic to asian text. And I use non-ascii latin characters with diacritics every day due to my language. Never had a failure due to ffmpeg.

However when I ran into issues with CLI programs it was always because whichever program that called it passed a broken path/filenames as arguments. I had troubles with batch files and Total commander for example.

PS:
Whoops. I meant the previous comment comment for #132.

**Comment by TheMainDude** [comment]
> @TheMainDude try getting a fresh FFmpeg from https://www.ffmpeg.org/download.html and point the extension to use the new FFmpeg.

I did install the latest FFmpeg but did not point the extension to it - I will attempt that now!!!

**Comment by mzso** [comment]
> @mzso please try https://github.com/inbasic/iaextractor/blob/beta/builds/feca4b87-3be4-43da-a1b1-137c24220968@jetpack-0.5.1b3.xpi?raw=true and let me know if the extension still fails to delete the tmp folder/file
> 
>     I don't understand why this addon puts files there pointlessly
> 
> FFmpeg is not good at handling non Unicode chars. That's the only reason.
> 

I just ran into this again. The temp files weren't cleared. Also the extensions still shows up as beta 1, even though it's shown as b3.
I rather disagree with the temp folder usage. Even if the addon were to remove the files after an error, I still get the error otherwise I wouldn't have.

**Comment by inbasic** [comment]
We are not copying files to temp directory anymore on the latest dev version

https://github.com/inbasic/iaextractor/blob/beta/builds/feca4b87-3be4-43da-a1b1-137c24220968@jetpack-0.5.2b1.xpi?raw=true
Please give it a try and let me know how it works.

**Comment by mzso** [comment]
Okay.

**Comment by mzso** [comment]
So far so good. Didn't see any issues.
