### ISSUE TITLE
Firefox freezes while video is being muxed

### ISSUE THREAD

**Issue by v-fox** [inbasic/iaextractor#134]
Pretty much all the time that I used the addon it got Firefox frozen while it was muxing the video with ffmpeg. It freezes for a few seconds after downloading audio and video, then it unfreezes and does nothing for a few more, then it freezes the FF pretty much for the whole time it creates the complete file while sometimes unfreezing for a brief moment and only when it's done everything is back to normal. Another popular Youtube downloading/muxing [addon](https://addons.mozilla.org/en-GB/firefox/addon/complete-youtube-saver/) doesn't freeze like that. The system is openSUSE Tumbleweed Linux, you can see the example of non-standard config options in this [prefs.js file](https://github.com/v-fox/live_opensuse_hsf/blob/e855318fca3e06f8ab39891dd6731a2cbb5c76dc/source/root/home/hacker/.mozilla/firefox/y30d7fz5.hacker/prefs.js) that I use for livecd FF profile that is similar to mine.

**Comment by inbasic** [comment]
YVAD executes FFmpeg as a child process. It is very unlikely it can block Firefox's process. Can you try the extension on a clean profile without modifying the pref.js and see if still has the same behavior or not?

**Comment by v-fox** [comment]
Yeah, just tried that. It's as if it had the highest I/O priority set for its R/W operations which would block everything else. What interesting is that the HTML5 Youtube video playback is not frozen while all inputs are ignored during this freeze. AFAIK, FF uses separate thread for HTML5 playback which is done also via ffmpeg.

**Comment by inbasic** [comment]
So you are still experiencing this even on a clean profile with the original prefs.js?

I am still not sure how a sub-process can block the main one. Even if FFmpeg is frozen, still the main process shouldn't.

Are you experiencing the same thing with the Media Converter extension as well?
https://addons.mozilla.org/firefox/addon/media-converter-and-muxer/

**Comment by v-fox** [comment]
> So you are still experiencing this even on a clean profile with the original prefs.js?

Yes, I've made new profile just for the test. I downloaded not a large file, about ~650mb, and had only 2 tabs open, while my main profile has hundreds listed and tens - loaded/active. It wasn't as long as with big files and as bad as on the main profile but still quite noticeable.

> I am still not sure how a sub-process can block the main one. Even if FFmpeg is frozen, still the main process shouldn't.

I didn't say that ffmpeg was frozen. It seems that, on the opposite, it takes all system I/O resources to itself while everything else, especially FF, freezes. Although, the FF (or at least, it's inputs, since I have OMTC & Azure enabled which should render FF's UI in a separate thread also) freezes for a second just before ffmpeg have actually started to producing muxed file.

My system is heavily tuned up for realtime and perfect system resource balancing which makes it especially bizarre. Even the heaviest, outrageous loads usually can't freeze up anything.

> Are you experiencing the same thing with the Media Converter extension as well?
> https://addons.mozilla.org/firefox/addon/media-converter-and-muxer/

Huh, I actually had it installed for a while because I thought that it extends functions of the downloader but now I actually used it for the first time. Using browser addon for filesystem operations is super cumbersome BUT it _did not_ freeze the browser while it was crunching at the file that was previously downloaded by the downloader.

**Comment by inbasic** [comment]
This issue is fixed on the latest dev version

https://github.com/inbasic/iaextractor/blob/beta/builds/feca4b87-3be4-43da-a1b1-137c24220968@jetpack-0.5.2b1.xpi?raw=true

Please give it a try and re-open if you are still experiencing this problem. If Firefox does not allow you to drop an unsigned XPI, open about:debugging and press "Load Temporary add-on"
