### ISSUE TITLE
One Click Mode shows two Save Dialogs

### ISSUE THREAD

**Issue by KaitoTriforce** [inbasic/iaextractor#136]
One Click Mode shows two Save Dialogs, one for the video track and another one for the audio track, which is not nessary since both get merged.

(OS X El Capitan 10.11.4, FF 46.0.1, AddOn 0.5.1)

**Comment by charlescanato** [comment]
Would like to add that I particularly like this "feature", specially when I intend to keep the audio track for later play, even though I'm downloading the vid. But can agree that if one chooses to auto remove these files, these two save dialogs might be really unnecessary.

**Comment by inbasic** [comment]
Thanks for the report. It is now fixed on the latest dev version. Please give it a try and re-open if you are still experiencing this issue.
https://github.com/inbasic/iaextractor/blob/beta/builds/feca4b87-3be4-43da-a1b1-137c24220968@jetpack-0.5.2b1.xpi?raw=true

If Firefox does not allow you to drop an unsigned XPI, open about:debugging and press "Load Temporary add-on"
