### ISSUE TITLE
error code -1

### ISSUE THREAD

**Issue by khfk** [inbasic/iaextractor#137]
What is the reason for this error?
The solution to this is the error?

![2016-05-14_045919](https://cloud.githubusercontent.com/assets/19354876/15265314/47a718b6-1996-11e6-8c9c-e32ab7d14a66.jpg)

**Comment by inbasic** [comment]
It means FFmpeg converter exited with an error. Do you get this for all videos? You can get a fresh copy of FFmpeg and point the extension to use it. https://www.ffmpeg.org/download.html

**Comment by khfk** [comment]
yes, i get tgis error for all videos and i install ffmpeg but error Still remains

**Comment by inbasic** [comment]
have you changed the default conversion commands?
