### ISSUE TITLE
Queued streames are not merged

### ISSUE THREAD

**Issue by v-fox** [inbasic/iaextractor#139]
On download of one DASH pair the addon works, but if you would download 2 or more pairs simultaneously, it doesn't bother to try merging the later ones, unless you would wait when the first one is finished. That's quite annoying.

**Comment by inbasic** [comment]
I am pretty sure YVAD is waiting for both audio-only and video-only pairs to be done before merging them. There are no queued streams.

**Comment by v-fox** [comment]
I have no idea what that supposed to mean but if there is more than 1 video downloading then all the others are not merged. It "waits" forever. Should I really explain why this is not right ? At least my video player can add external audio, so I don't care much.
