### ISSUE TITLE
Doesnt show all downloadable formats

### ISSUE THREAD

**Issue by ekaris** [inbasic/iaextractor#140]
For example using this link there is no download option for 1080p but the video is available in that format:
https://www.youtube.com/watch?v=J4z5TaApMTQ

**Comment by inbasic** [comment]
Unfortunately there is no fix for this. YouTube has started to splitting each DASH file into several segments. If we want to support this, we need to download all segments separately and then merge them together in order to have one DASH stream. Then we will need to combine video-only and audio-only stream to get the actual file. It is just too much operations!

**Comment by ekaris** [comment]
Has started recently? It means that there will be no support in the future to download most files?

**Comment by inbasic** [comment]
Most likely there will be no support for these kind of streams, unless someone wants to work on it and request a pull.

**Comment by ekaris** [comment]
But it is happening recently? And for example: https://www.youtube.com/watch?v=DWfxAuUw-D4&index=5&list=ELM6p27Ly6WWw 
Why this video doesn't have opus download option while all the others have? Ive seen this on other webseries, only 1 doesn't have opus option... why?

**Comment by inbasic** [comment]
In the latest dev version you can see whether segmentation is skipped or not;
https://github.com/inbasic/iaextractor/blob/beta/builds/feca4b87-3be4-43da-a1b1-137c24220968@jetpack-0.5.2b2.xpi?raw=true

Download the XPI and use "about:debugging" to load it.
In the error console (Ctrl + Shift + J), itag number for skipped items are displayed.

> But it is happening recently?

I am not sure when this feature has been enabled on YouTube.

> Why this video doesn't have opus download option while all the others have?

No idea. There is no segmentation for this video.

**Comment by ekaris** [comment]
Is there a way to download private videos?
https://www.youtube.com/watch?v=-yhr7_V-A0E&index=10&list=PLZLTS4u9M_2rYRUMj5RoI016wS_JxRnGE&t=56s
