### ISSUE TITLE
In File-naming pattern [published_date] always yields an empty string 

### ISSUE THREAD

**Issue by TadeuszSobol** [inbasic/iaextractor#143]
i.e:
[file_name]_[published_date].[extension]
is equal
[file_name]_.[extension]

**Comment by inbasic** [comment]
What is the format of the date in the details section of a page;
![screen shot 2016-07-06 at 12 51 13](https://cloud.githubusercontent.com/assets/351062/16611732/6368b120-4378-11e6-8fbf-b81f6851c01f.png)

**Comment by inbasic** [comment]
I am going to use a new method in the upcoming release. Please wait for the new version and reopen if you are still experiencing this issue.
