### ISSUE TITLE
Why can't I download in my preferred format? (FLV)

### ISSUE THREAD

**Issue by x-Mysterion-x** [inbasic/iaextractor#146]
When I click on "Quick Download" it's always downloaded in MP4. It's not in my preferred format.

**Comment by inbasic** [comment]
Are you sure there is an FLV format offered by the video? Have you checked all the possible formats?

**Comment by x-Mysterion-x** [comment]
Yes. It makes me this on every videos I download.

**Comment by inbasic** [comment]
FLV is not avaiable anymore for most videos. Try the "inject menu" to see all available formats.
