### ISSUE TITLE
How to uninstall ffmpeg installed via Firefox addon YouTube Video and Audio Downloader 0.5.2?

### ISSUE THREAD

**Issue by freaxG** [inbasic/iaextractor#148]
After ffmpeg is installed, YouTube Downloaders ( Firefox addon YouTube Video and Audio Downloader,YouTube-dlg,ClipGrab,4K Video Downloader,etc) can't handle the .flv video format.  

How to uninstall ffmpeg installed via Firefox addon YouTube Video and Audio Downloader 0.5.2?

And... What should I do let YouTube Downloaders (YouTube-dlg,ClipGrab,4K Video Downloader,etc) can handle the .flv video format?

My OS is Ubuntu 14.0.4.2 LTS 

related article : http://askubuntu.com/questions/791164/how-to-uninstall-ffmpeg-installed-via-firefox-addon-youtube-video-and-audio-down

**Comment by inbasic** [comment]
> How to uninstall ffmpeg installed via Firefox addon YouTube Video and Audio Downloader 0.5.2?

Just open your profile directory. There is an ffmpeg executable there. Delete the file; that's it.

> And... What should I do let YouTube Downloaders (YouTube-dlg,ClipGrab,4K Video Downloader,etc) can handle the .flv video format?

You just need to have a working FFmpeg. Install it with apt-get and then find the path and insert it in the options page.

**Comment by freaxG** [comment]
How to insert .flv video format option in FFmpeg?

**Comment by inbasic** [comment]
There is no need to insert FLV video format. I am not sure what you are trying to do. If you just want to get the FLV format, then click on the download button below the player to let the extension find all formats. Now select the FLV one if there is any FLV format for this particular video. If FFmpeg is installed, the extension will extract the audio for you as well.

**Comment by freaxG** [comment]
I can't handle flv video format in YouTube Downloaders (Firefox addon YouTube Video and Audio Downloader 0.5.2,YouTube-dlg,ClipGrab,4K Video Downloader,etc) after ffmpeg installed.

**Comment by inbasic** [comment]
FFmpeg installation cannot cause this problem. You can confirm this by installing one of the downloaders on a clean profile where FFmpeg is not installed; https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by freaxG** [comment]
I remove firefox profiles. But I can't uninstall ffmpeg. Below is ffmpeg related files lists.
How to uninstall ffmpeg (all of the ffmpeg related files)? 

/var/cache/apt/archives/chromium-codecs-ffmpeg-extra_50.0.2661.102-0ubuntu0.14.04.1.1117_amd64.deb
/var/lib/dpkg/info/chromium-codecs-ffmpeg-extra.md5sums
/var/lib/dpkg/info/chromium-codecs-ffmpeg-extra.list
/usr/bin/ffmpeg
/usr/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py
/usr/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.pyc
/usr/lib/chromium-browser/libs/libffmpeg.so
/usr/lib/x86_64-linux-gnu/oxide-qt/libffmpeg.so
/usr/lib/x86_64-linux-gnu/gstreamer-0.10/libgstffmpegcolorspace.so
/usr/share/doc/chromium-codecs-ffmpeg-extra
/usr/share/app-install/desktop/gstreamer-ffmpeg.desktop
/usr/share/lintian/overrides/chromium-codecs-ffmpeg-extra

**Comment by inbasic** [comment]
You are not supposed to remove ffmpeg used in other projects. The one that is installed by this extension is a single executable located in your Firefox profile. If you remove these files some of your programs will stop working.
