### ISSUE TITLE
Use with Download Scheduler

### ISSUE THREAD

**Issue by KitchM** [inbasic/iaextractor#149]
How can I use this with the Download Scheduler add-on?  With satellite Internet, we must schedule downloads in early AM hours.

Thanks.

**Comment by inbasic** [comment]
It is impossible. Even if we work on integration, still YouTube does not allow you to get a file that is generated a few hours age. There is a time span that YouTube allows a link

**Comment by KitchM** [comment]
What do you mean by "a file that is generated a few hours age"?  These videos have been available for years.
