### ISSUE TITLE
File naming issues in 0.5.3.1

### ISSUE THREAD

**Issue by Anamon** [inbasic/iaextractor#150]
Since the last update to 0.5.3.1, I have started noticing issues with the naming of target files when a different filename is entered in the save dialogue.

- When downloading a regular stream, entering a new filename without extension in the save dialogue will no longer automatically append the extension to the file, even though the filetype dropdown shows it. For example, downloading an MP4 stream and entering "MyFile" as the file to save to, even though the dropdown shows "Video File (*.mp4)", the file will be saved as "MyFile" instead of "MyFile.mp4" Previous versions used to append the extension if it was not entered.
- For DASH streams, what I assume is the same bug leads to the audio and video streams no longer being muxed with FFMPEG, if a different name without extension is entered in the save dialogue. This, too, worked in previous versions.

I am using version 0.5.3.1 of the extension for Firefox 47.0.1 on Windows 7 Professional x64.

**Comment by inbasic** [comment]
This should get fixed on 0.5.4. Thanks for the report. Please reopen if you are still experiencing this issue on the new release.
