### ISSUE TITLE
Ffmpeg error with Firefox x64

### ISSUE THREAD

**Issue by ggpetrov** [inbasic/iaextractor#155]
I just installed the x64 version of Firefox, and the plugin works fine, but when i'm triyng to use audio extraction with Ffmpeg x64, I get error mesage : Ffmpeg error code -1, and nothing happens.

**Comment by inbasic** [comment]
Are you sure FFmpeg is installed properly. To make sure just get it manually and point the extension to use the downloaded FFmpeg executable from options page; https://www.ffmpeg.org/download.html

**Comment by ggpetrov** [comment]
I just did everything, like with the x86 version. The only difference was the version of FFmpeg wich your plugin downloaded automaticaly.
