### ISSUE TITLE
Downloads stuck "Extracting Audio File"

### ISSUE THREAD

**Issue by Domo1139** [inbasic/iaextractor#162]
Hi,

Ever since a few days ago I have been unable to download any file using this addon, I am using the latest Firefox version and I have done a full refresh to no avial. No matter the file or format I choose to download I download the "- DASH" version fine but then it is infinitely stuck extracting the file - even after restarts of firefox. I tried disabling the extracting audio file feature but this did not change anything in the slightest; any possible solutions/suggestions? Thanks.

**Comment by inbasic** [comment]
Try to get a fresh copy of FFmpeg from https://ffmpeg.org/download.html. Then point the extension to use the newly download executable from the options page and see if it helps.

**Comment by Domo1139** [comment]
Perfect, thank you so much!


________________________________
