### ISSUE TITLE
Cannot connect to the Signature Server

### ISSUE THREAD

**Issue by ukbloke** [inbasic/iaextractor#173]
YouTube Video and Audio Downloader 0.5.6 for Firefox 51.0.1 (32-bit) is no longer working.

My current Youtube selection is  https://www.youtube.com/watch?v=WVraWA1FGkU

When "Download" button is selected the error message "Error: Cannot connect to the Signature Server" is reported.

**Comment by hairymonkeynuts** [comment]
I have multiples where the spinner just spins. Almost all videos now. Multiple machines. I know one is 51.0.1 x64, another is probably same version. 0.5.6 of add-on as well.

**Comment by hairymonkeynuts** [comment]
Sorry, this seems duplicated.   See:  https://github.com/inbasic/iaextractor/issues/169

**Comment by ukbloke** [comment]
Thank you hairymonkeynuts for your super prompt reply. 

I have applied the fix as in  #169 and now all is tickety-boo.

Cheers!
