### ISSUE TITLE
Cannot connect to the Signature Server 

### ISSUE THREAD

**Issue by ZootHero** [inbasic/iaextractor#174]
For some videos the downloader works, for others not. Seems there is a restriction in Google/YouTube

**Comment by ZootHero** [comment]
In version 0.57 the issue is resolved

**Comment by ivanov007** [comment]
today I'm getting this error again, I'm using 0.58, so I guess youtube just changed something on their side...

**Comment by richardhering** [comment]
Me too.

Error: Cannot connect to the signature server.

Is there a workaround yet?

**Comment by inbasic** [comment]
follow https://github.com/inbasic/iaextractor/issues/191
