### ISSUE TITLE
Excessive loading time, Files save as "undefined"

### ISSUE THREAD

**Issue by bluzc** [inbasic/iaextractor#182]
iaextractor takes several minutes to load and saves all downloaded files as "undefined"  I have uninstalled and reinstalled iaextractor several times. Reset all options to defaults. Still the same problem

**Comment by inbasic** [comment]
This seems like a profile damage to me; try it on a clean profile and report back; http://blog.add0n.com/2016/01/30/how-to-use-firefox-profile-manager.html
