### ISSUE TITLE
problem in video without audio

### ISSUE THREAD

**Issue by DavidBrenner3** [inbasic/iaextractor#183]
Hi,

Very good software, thank you.

Just a small problem.
I am a computer programmer (Delphi, C++).
I made a small tool that extracts frames from video files. It works fine for almost all types.
Specifically I am using DSPack to capture the frames while playing the video with no sound in background.
But when trying this on video files with no audio downloade dwith your tool (any resolution, mp4 or webm), it starts losing frames (= it waits but doesn't receive the bitmap in the buffer).
With other Youtube downloaders don't have this problem (but they're downloading with sound).
As codecs I use Lav filters and/or K-Lite codecs.

If I download with audio and try to remove it after, all is ok.

I am not 100% sure what exactly could be the problem but can you please help me figure out?

Thank you.

**Comment by inbasic** [comment]
Those video-only files are [special containers](https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP) that most likely your tool is not familiar with. Either use FFmpeg in your program to extract frames or use Media Converter add-on to convert the files first and then feed them to your program.

**Comment by inbasic** [comment]
> With other Youtube downloaders don't have this problem

You mean they can grab video-only (DASH) streams and still your tool work fine?

**Comment by DavidBrenner3** [comment]
Thank you for fast reply.

This is my tool (binaries): https://drive.google.com/open?id=0ByKxAD_t9uvLOVJsUVc4aXlTT0U
It's not finished (still Beta). 
Just use the import video command.

I know about ffmpeg and Media Converter addon but I prefer to use them as a last resort.
My tool plays fine these video-only files, it's just having problems capturing frames from them.
Do you know a better video codec for this?


    With other Youtube downloaders don't have this problem

You mean they can grab video-only (DASH) streams and still your tool works fine?

I said in paranthesis: (but they're downloading with sound). So they're not video-only (DASH) streams.

**Comment by inbasic** [comment]
Unfortunetly I am not a Windows user and hence cannot try the tool. Still I believe this is not a codec issue. Most likely DSPack has a problem with decoding DASH containers. You can confirm this by using the Media Converter add-on and combine a single DASH file with its audio and see if your tool can create animated JPEG from the output. Note that MC add-on is not going to change the coding of input files when muxing them together.

Also this thread might be of your interest: https://superuser.com/questions/556029/how-do-i-convert-a-video-to-gif-using-ffmpeg-with-reasonable-quality

**Comment by DavidBrenner3** [comment]
It appears it's a video codec problem after all: https://github.com/Nevcairiel/LAVFilters/issues/129
It seems these video files can be handled well only by a very few players (like VlcPlayer).
The rest of the players have problems playing them.

Since you're on Linux and not using Windows, I can understand why it seems not that important.
