### ISSUE TITLE
Can't find code for versions 0.5.1 through 0.5.7

### ISSUE THREAD

**Issue by BC-GitHub** [inbasic/iaextractor#184]
I am new to Git, GitHub. So, please forgive me if I am overlooking something.

Have you released the source code for the most recent versions of the downloader: > 0.5.0?

If not, are you planning to release the code?

**Comment by inbasic** [comment]
Beta channel has up-to-date code; https://github.com/inbasic/iaextractor/tree/beta

I am going to update the master branch too. Thanks for the report.

**Comment by BC-GitHub** [comment]
Thank you.
I like how clean, well structured your code is.
