### ISSUE TITLE
no download button in new youtube interference

### ISSUE THREAD

**Issue by promisekun** [inbasic/iaextractor#186]

**Comment by grssam** [comment]
To experience the new youtube interface, run this JS in console on youtube page and reload.

`document.cookie="VISITOR_INFO1_LIVE:'fPQ4jCL6EiE'"`

**Comment by yekohat** [comment]
As the new Youtube layout is enabled by default, I, and @promisekun I think, cannot see the download button anymore.

Quick and temporary fix: You can disable the new layout by clicking on your profile but I'm not sure that this button will stay there forever.

**Comment by inbasic** [comment]
This should have been fixed on the next release. Also you can try the new WebExtension version which supports the new material design as well; https://addons.mozilla.org/en-US/firefox/addon/youtube_downloader_webx/

Please reopen if you still have issue after updating to 0.5.8
