### ISSUE TITLE
AVC video + Opus audio

### ISSUE THREAD

**Issue by Metaphorce812** [inbasic/iaextractor#189]
This isn't exactly a bug, so much as a feature request, but I didn't no where else to put it.
So it seems that YouTube has completely done away with their 192k AAC audio (both integrated into video and as DASH). That means that the highest quality audio now available is Opus. But the highest quality video is still AVC.
So I was wondering if you could add an option to download DASH streams of AVC and Opus and set up FFMPEG to merge them into an MKV file (since MP4 doesn't support Opus). Because right now I have to download both streams separately, use MKVToolnix to merge them/remove the 125k AAC track, then delete the original files to save a video from YouTube with the best possible A/V quality (which is kind of the purpose of this program right?). 
I'd really appreciate it if you could add this feature, and thanks for all your hard work!

**Comment by inbasic** [comment]
I added support for muxing with OPUS audio-only for all types of containers in the new WebExtension version.

You can give it a try here: https://addons.mozilla.org/en-US/firefox/addon/youtube_downloader_webx/

Thanks for the report
