### ISSUE TITLE
Exception: Component is not available (NS_ERROR_NOT_AVAILABLE)

### ISSUE THREAD

**Issue by KeithPGR** [inbasic/iaextractor#190]
![image](https://cloud.githubusercontent.com/assets/20356319/25783395/c21fb8f2-3329-11e7-813f-11b3d5724c78.png)

Sometimes when loading a YouTube video, I click the button in the menu bar to "quick download" (one-click mode), it gives this error. I have to wait a couple seconds and try again, or sometimes, refresh the page.

Maybe it's simply saying that it can't download the stream yet? If so, the exception handler could be intercepted to say that.

p.s. Love the add-on though.

**Comment by inbasic** [comment]
I am not sure what this error is! What is your Firefox version? 

btw, we are gradually moving to the WebExtension version (https://addons.mozilla.org/en-US/firefox/addon/youtube_downloader_webx/) and in this version since the downloading API is different this bug would not be an issue.

**Comment by KeithPGR** [comment]
I'm using FireFox version 53.0 (at the time of the post). I just updated to 53.0.2 today.

I tried installing your link, but Firefox is blocking me. I tried setting **xpinstall.signatures.required** to FALSE, but it still won't let me install the add-on.

p.s. I'm not the person who left a 1-star review for a similar problem.

**Comment by inbasic** [comment]
The WebExtension version cannot be installed this way as it is not yet reviewed by Mozilla. For now, you need to follow the method pointed in the description (install as a temporary add-on). 

I am currently trying to get feedback on how the WebExtension port is working before merging it into the original add-on.

**Comment by KeithPGR** [comment]
Gotcha. I should've read the installation instructions more carefully. Sorry.

It works, although the convenient one-click mode isn't available anymore, which is something I specifically use the add-on for.

Also, the  "Quick Download" button doesn't do anything. It says "Please Wait..." and then resets back to "Quick Download" and nothing happens.

**Comment by inbasic** [comment]
> Also, the "Quick Download" button doesn't do anything.

It is fixed now

> one-click mode 

It is not yet implemented. I will!
