### ISSUE TITLE
Tool no longer works for any video : Cannot contact to the signature server

### ISSUE THREAD

**Issue by Tectract** [inbasic/iaextractor#191]
Tool permanently broken now?

**Comment by NuitTombee** [comment]
I get that for older videos but some recent uploads allow me to download them still.

**Comment by Tectract** [comment]
I'm unable to diagnose the issue further without further guidance.

**Comment by NuitTombee** [comment]
I don't know if it's helpful, but these two are just days apart and I can't download one but not the other.

Can: https://www.youtube.com/watch?v=p-o_bMkzOW0
Can't: https://www.youtube.com/watch?v=6uI73qTiqwE

**Comment by AAubin17** [comment]
I have tested NuitTombee links with same results.
Other examples if it might help any dev:
Works fine https://www.youtube.com/watch?v=LS7e43qVpbE
Does not work https://www.youtube.com/watch?v=EdQP7sgbvoA

**Comment by M3T4SP01LT** [comment]
Confirmed on 3 vm's ff v53.0.2+v0.5.8,nothing in error console.
 I appreciate the amount of work involved with this bug,hope the dev(s?)can get it sorted,and keep this great add0n alive!. :)

Ppl plz bare in mind that starting with ff v53.x through ff v57.x mozillla is pushing major changes(yes we're all guinea pigs....lol ;),not to mention dropping legacy add0ns ;(boooo! ),so this is to be expected to be honest,and requires bundles of work from the dev's,in fact it looks like some addon dev(s) are throwing in the towel->https://mail.mozilla.org/pipermail/dev-addons/2016-December/002367.html

Mozilla explaining the addon situation for ff v53.x through ff v57.x -> https://blog.mozilla.org/addons/2017/02/28/compatibility-for-firefox-53/

@Dev(s),nice work and many thx for porting the Media Converter and Muxer to a web extension,it's the only ffmpeg gui for me!,donation forthcoming :)

Highest regards M3T4SP01LT

**Comment by inbasic** [comment]
Thanks guys, it is fixed on 0.5.9
https://github.com/inbasic/iaextractor/blob/master/builds/0.5.9.xpi?raw=true

It is still not signed so you need to install it as a temporary add-on for testing.

1. Download the XPI
2. Open about:debugging and point "Load Temporary Add-on" to the downloaded XPI

**Comment by inbasic** [comment]
WebExtension version is also fixed; https://addons.mozilla.org/en-US/firefox/addon/youtube_downloader_webx/
