### ISSUE TITLE
Pale Moon compatibility

### ISSUE THREAD

**Issue by LummoxJR** [inbasic/iaextractor#55]
Newer versions of this extension are no longer compatible with Pale Moon 24.x or 25.x. In Pale Moon 24.7 I can report that the icon does not appear in the toolbar, even after forcibly updating the .xpi file to fool the browser into accepting the add-on as compatible. There are a lot of Pale Moon users (since the switch to Australis, a lot of Firefox users jumped ship) waiting for this add-on to be available again.

**Comment by inbasic** [comment]
I am closing this as for now there is no way to make the latest version compatible with PM.
