### ISSUE TITLE
How to download the original audio file with the Java Script?

### ISSUE THREAD

**Issue by Javin5** [inbasic/iaextractor#59]
I installed your YouTube Video and Audio Downloader 0.4.2 in Firefox. You say that there is a JavaScript, which downloads the original audio file. However, I find only a list of aac and ogg vorbis audio files to choose from, and no mp3 files (ffmpeg is installed and JavaScript is enabled). I don't see any field to click on that says "download original audio via JavaScript" or similar. How do I do this???

**Comment by thenoncoder** [comment]
mp3 sucks. ogg is better. that's why!
