### ISSUE TITLE
Slow response and filenames are "undefined".

### ISSUE THREAD

**Issue by Ailtekon** [inbasic/iaextractor#62]
When I click the "Download" button, the "Download Links" window appears but spins for about a  minute before showing the links list.  When you click a link, it's another minute before it starts downloading.  The title of the download is always "undefined" rather than the video title.  Otherwise the download works fine. I am running Firefox 34.0.5 on Windows 8.1

I have tried:
- Clicking "Reset" at "Reset all setting".
- Clicking "Proceed" at "Download and configure ffmpeg..." to redownload ffmpeg.exe
- changed just about every setting in the options without any effect.
- Remove and add back in the plugin.
- Resetting Firefox to default state.

**Comment by inbasic** [comment]
Can you confirm the problem on a clean profile as well?
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

> When I click the "Download" button, the "Download Links" window appears but spins for about a minute before showing the links list. 

Well the downloader needs to get a few info from YouTube server and time depends on your speed. A minute is too long though!

> When you click a link, it's another minute before it starts downloading. 

In the latest version there should be no delay at all. Are you sure you are on the latest version of the extension?

> The title of the download is always "undefined" rather than the video title. Otherwise the download works fine. 

You need to left click on the items rather than right click. Is this what you are doing?

**Comment by Ailtekon** [comment]
I created a new profile, installed only the Youtube Video and Audio Downloader 0.4.2, and it behaved exactly the same.  I'm using left click.  It shouldn't be an issue with speed, it's a high end gaming PC and my internet can stream multiple 1080p videos simultaneously.  I tried another Youtube downloader, and it is working fine.  

After some experimentation, it seems the second delay (when clicking a link in the menu) doesn't always happen.  When it does happens, so far it seems it's always to be a "video only" link.

I have a Windows 7 computer here too, and it behaves fine, no delays at all and the file names match the video titles.

**Comment by inbasic** [comment]
Okay then.

Open a YouTube page, then open the error console (Ctrl + Shift + J). clear the window, and uncheck all tabs except JS and LOG. Now click on the download button and let the extension generate the links. Send me an screenshot of the console window.
