### ISSUE TITLE
mp4 m4a combining

### ISSUE THREAD

**Issue by hannelius** [inbasic/iaextractor#63]
hello again...
the downloader extension is working great for me
but i had so many problems with getright
that i started using downthemall

it downloads really fast for me
but the latest version 2.0.17 wouldn't save the DASH filenames properly
so i couldn't use it there...

just today i found out there's a 3.0 beta5
and it saves the filenames just as they should be
but they won't combine when the downloads are finished

so i used media converter and muxer (thanks!)
to drag the two files to like i usually do
but when i do it shows a circle with a line through it
and it won't accept them...

they seem to have downloaded ok
the file sizes are what they should be
and when i play the video only it plays just fine
so i wonder what the trouble could be
any clues?

**Comment by inbasic** [comment]
> it downloads really fast for me
> but the latest version 2.0.17 wouldn't save the DASH filenames properly
> so i couldn't use it there...

Have you followed the integration instruction here?
http://firefox.add0n.com/extractor.html, FAQ 4

> so i used media converter and muxer (thanks!)
> to drag the two files to like i usually do
> but when i do it shows a circle with a line through it
> and it won't accept them...

Not sure why. Maybe file extensions are not acceptable. Try the integration instruction and let me know if the converter still has the problem with the downloaded files.

**Comment by hannelius** [comment]
must have been a fluke...
i uninstalled some bloatware
and rebooted a couple times and tried it again
and it saved and combined them just fine
even the ones i tried before...

the only thing is the media converter
leaves the DASH in the filenames...

yes, i relooked at the faq page a few weeks ago
and saw how to use a download manager instead of firefox
and i've been doing it that way ever since...

the reason i switched to beta5
is that the regular version would save the DASH ones
as medium.mp4 etc and it was confusing
to know which ones were which
and this one, the beta5
saves them as they should be

thanks for your help
i tried another downloader for youtube
and deleted it after a minute...

**Comment by inbasic** [comment]
Try the latest version, 0.1.1. The bug of keeping "- DASH" is fixed in this version,
https://addons.mozilla.org/en-US/firefox/addon/media-converter-and-muxer/versions/

> one thing i forgot to mention
> when i use downthemall i need to download both DASH ones separately
> and combine them with the muxer
> but with firefox it downloads both at once
> and combines them like it should
> since beta5 i think...

With Firefox's download manager, the extension can listen over download process, but with dTa or an external downloader there is no such a listener, that is why the files are kept uncombined.

**Comment by hannelius** [comment]
with dTa or an external downloader there is no such a listener
oh, i see...

i've been using dta with it for two days now with no problem at all
and the muxer combines them really quick

        Try the latest version
thank you...
thank you for making it so easy...
