### ISSUE TITLE
it doesn't work with new Firefox 35.0

### ISSUE THREAD

**Issue by sucadance** [inbasic/iaextractor#64]
This plug-in doesn't work anymore in Firefox 35.0

**Comment by Javin5** [comment]
I have Firefox 35.0 on Windows 8.1 and it works flawless.

However, I still don't know which one of the available choices is the ORIGINAL audio file as it was uploaded to YouTube.

**Comment by pasmanp** [comment]
Works in Firefox 35, Mint 17.
 
Always the best audio file is downloaded (regardless of "always download highest audio" is off)

**Comment by inbasic** [comment]
@sucadance please try the extension on a clean profile
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles
There might be conflicts with another extension of yours.

@Javin5 I think none of them is the original one (uploaded to YT), however, if you get the highest quality "audio-only" item, it would be the highest available quality in YT server.

**Comment by Javin5** [comment]
I support inbasic's idea about a potential conflict in sucadance's installation; retrying on a new, clean Firefox install may help. I personally found the plugin to be very stable across several Firefox upgrades.

**Comment by sucadance2** [comment]
I found the cause of this malfunction, I have disabled dom.storage.enabled and dom.dbindexed.enabled from about:config. Now, I have re-enabled them and it works.
