### ISSUE TITLE
How to get 4k video with sound ?

### ISSUE THREAD

**Issue by castaway-** [inbasic/iaextractor#65]
Hi,

The videos from youtubes always comes with 720p maximum with sounds.
Whenever we need 2160p, it's "video only"

Any ideas ?
Thanks!

**Comment by inbasic** [comment]
If you have FFmpeg installed, the addon will download a proper audio file for "video-only" items and when both are downloaded, they will be combined automatically.

To install FFmpeg, go to the options and press on "Proceed" button.

**Comment by castaway-** [comment]
Thank you for the answer.
I'll try that !!
