### ISSUE TITLE
Download fails

### ISSUE THREAD

**Issue by devendrap** [inbasic/iaextractor#67]
Hi,

Download is failing consistently with error 

TypeError: info.response undefined

Below is the youtube link in error: 
https://www.youtube.com/watch?v=q-0aYfF4kb0

Regards,
Devendra

**Comment by zelenin** [comment]
https://www.youtube.com/watch?v=iux9mTnf7xg&feature=youtube_gdata

**Comment by marklieberman** [comment]
I'm getting the same error on pretty much every video now.
![yvderror](https://cloud.githubusercontent.com/assets/6473247/5932541/c017b34c-a67d-11e4-89e5-5abe65f5880e.png)

**Comment by DJMikiej** [comment]
I concur ... You tube changed something ... again ;-)

**Comment by inbasic** [comment]
It should be fixed on version 0.4.3,
https://addons.mozilla.org/en-US/firefox/addon/youtube-video-and-audio-dow/versions/

**Comment by bb14753** [comment]
Ahh, the update I've been awaiting. Back to good again, thanks @inbasic
