### ISSUE TITLE
TypeError: dashmpd is undefined

### ISSUE THREAD

**Issue by touristinexile** [inbasic/iaextractor#68]
When i press the download button the orange, i think injected, field opens with the spinning circles and then the tab up top shows "TypeError: dashmpd is undefined. I've checked for updates and reset firefox to default.  I've also updated java. this is a problem i am having with the Youtube video and audio downloader

**Comment by inbasic** [comment]
The problem is fixed on the latest version,
https://addons.mozilla.org/en-US/firefox/addon/youtube-video-and-audio-dow/versions/
