### ISSUE TITLE
TypeError: info.response is undefined.

### ISSUE THREAD

**Issue by jtvilm** [inbasic/iaextractor#69]
Hi,

I am trying to download a particular video and get this error. 

It happens with the following videos (all different videos but identical artist and title):
https://www.youtube.com/watch?v=uZyZ2puuD08
https://www.youtube.com/watch?v=AyS78h4Trlw
https://www.youtube.com/watch?v=67hvG7IZNLQ

Just wanted to let you know that error occurs. It is the first time I encounter an error with this FF addon. The only one that can download YouTube videos properly.

Thanks and keep up  the good work!

**Comment by Rokeugon** [comment]
yep im getting the same problem as well with numerous amount of videos, its odd because this has never happened in the many years of me using this addon

**Comment by bacon-cheeseburger** [comment]
Add me to the list as well. I heard that youtube defaults to HTML5 instead of flash now. Maybe that has something to do with it? At any rate, this problem is definitely there on a growing number of videos.

**Comment by xvolution** [comment]
I get the same error as well. I'm assuming Youtube updated something to try blocking downloader apps. The only videos that don't seem to be affected are ones with only low quality download options.

**Comment by bb14753** [comment]
Same problem here.

**Comment by touristinexile** [comment]
I don't think youtube would do something to block the "youtube video and audio downloader" What I don't understand is Mozilla's silence on the issue.  I use the downloader a lot and keepvid just doesn't do the same job.

**Comment by touristinexile** [comment]
I just did this and it worked You loose all your bookmarks and have to download everything and reconfigure it but the yt v and a downloader works.

@sucadance please try the extension on a clean profile
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles
There might be conflicts with another extension of yours.

I was afraid to try this because it seemed really technical but it wasn't. If i had to do it all again I might just create a new profile and make that the default one and not remove the other

**Comment by bb14753** [comment]
@touristinexile I first tried the refresh, but that didn't work. So I deleted the profile, uninstalled, deleted, re downloaded, then re installed mozilla, created a new profile, and am still getting the same error message

**Comment by touristinexile** [comment]
if everything you have done has not worked try contacting @sucadance where i got the profile thing. They may have more ideas.  I did the mozilla reinstall and it did not work.  It did when i just did the profile thing making a new one and removing but not deleting the old one.  I really feel bad this didn't work I download a lot of videos and it was hell.

**Comment by bacon-cheeseburger** [comment]
inbasic, thanks for the fix!

**Comment by inbasic** [comment]
Great!
