### ISSUE TITLE
v0.4.3 not detecting f313

### ISSUE THREAD

**Issue by sdsucks** [inbasic/iaextractor#70]
support for f313 was added in v0.4.2 but broken in v0.4.3

https://www.youtube.com/watch?v=uHQF44bn6Ts

**Comment by inbasic** [comment]
Is this fixed on 0.4.4b1?
https://addons.mozilla.org/en-US/firefox/addon/youtube-video-and-audio-dow/

**Comment by sdsucks** [comment]
yes, it detects f313 again
