### ISSUE TITLE
Support for Opus audio stream

### ISSUE THREAD

**Issue by gwarser** [inbasic/iaextractor#72]
https://www.youtube.com/watch?v=1FH6NSPyj18

![opus251](https://cloud.githubusercontent.com/assets/886325/6096046/6437d170-af7d-11e4-95eb-17be27f56dbd.png)

	General
	Complete name                            : videoplayback.webm
	Format                                   : WebM
	Format version                           : Version 4 / Version 2
	File size                                : 64.0 KiB //first sample
	Duration                                 : 5mn 42s
	Overall bit rate                         : 1 531 bps
	Writing application                      : google
	Writing library                          : google
	
	Audio
	ID                                       : 1
	Format                                   : Opus
	Codec ID                                 : A_OPUS
	Duration                                 : 5mn 42s
	Channel(s)                               : 2 channels
	Channel positions                        : Front: L R
	Sampling rate                            : 48.0 KHz
	Compression mode                         : Lossy
	Language                                 : English
	Default                                  : Yes
	Forced                                   : No

**Comment by inbasic** [comment]
So is this a new itag that the extension is not supporting?

**Comment by gwarser** [comment]
Yes. I can'not download Opus audio (251), only OGG/Vorbis is supported.

**Comment by arcm111** [comment]
i found all these new itags, you might wanna add them:
	59:   ["mp4", "480", "aac", 128, NULL],
	78:   [array ("mp4", "480", "aac", 128, NULL],
	249: [array ("webm", "48", "opus", 50, "a"],
	250: [array ("webm", "48", "opus", 70, "a"],
	251: [array ("webm", "128", "opus", 160, "a"]

**Comment by inbasic** [comment]
I added support for `OPUS` format. However, by default `OPUS` formats are ignored by video and audio combiner. Seems like many players cannot play the combined file.
https://addons.mozilla.org/firefox/downloads/file/310746/youtube_video_and_audio_downloader-0.4.4b2-fx.xpi?src=devhub

**Comment by gwarser** [comment]
>However, by default OPUS formats are ignored by video and audio combiner. Seems like many players cannot play the combined file.

Checked `Consider OPUS...` - works fine on MPC-HC.

Thank you.
