### ISSUE TITLE
Available Downloads List Longer with FFmpeg Installed

### ISSUE THREAD

**Issue by TrygonSystems** [inbasic/iaextractor#73]
When FFmpeg is installed the list of available downloads has more items in it, in particular M4A AAC 256K.  Why is this? I would have thought that the available downloads would be determined solely by what YouTube is offering.

**Comment by inbasic** [comment]
> I would have thought that the available downloads would be determined solely by what YouTube is offering.

That's true! Are you sure it is FFmpeg dependent?
