### ISSUE TITLE
Youtube downloader

### ISSUE THREAD

**Issue by Armanshah1** [inbasic/iaextractor#76]
Youtube downloader stopped exctracting audio after video.
What happened. Reinstalling didn't help.

**Comment by inbasic** [comment]
Make sure you have FFmpeg on your system and the path is set correctly in the settings.

**Comment by Armanshah1** [comment]
Of course I have FFmpeg on my system! I told that the add-on did audio
extraction before, but stopped doing that unexpectedly. Don't know what is
reason.
If it worked yesterday so the path in the settings was right. Why should it
stopped working today though I didn't change anything!

**Comment by inbasic** [comment]
What is your OS?

**Comment by Armanshah1** [comment]
Windows 7

**Comment by Armanshah1** [comment]
Ok, I checked the path and found out that there is no ffmpeg.exe file in
that folder. But how can it be so? Yesterday the add-on worked perfectly!
Extracted all the audios. Withouth that file?

On Fri, Feb 27, 2015 at 4:51 PM, Arman Shahbazyan <armanshahbazyan@gmail.com
> wrote:

> Windows 7
>

**Comment by inbasic** [comment]
Have you moved your Firefox profile? If not maybe a Windows cleaner deleted the file. Anyhow, just get a fresh copy from https://www.ffmpeg.org/download.html and point the extension to the new executable.

**Comment by Armanshah1** [comment]
Ok, thanks for support, but the solution was in the add-on.
There is a button in options of add-on - "Download and configure FFmpeg
audio converter"
On the bottom of options. "Proceed" will repair the ffmpeg error.
But I suggest developers make that option to check the ffmpeg
AUTOMATICALLY, so after installing and reinstalling users will not meet
such problems.
Thanks.
