### ISSUE TITLE
'256k audio only' no longer an available download option for Youtube videos

### ISSUE THREAD

**Issue by bobn42855** [inbasic/iaextractor#77]
For the last several days, '256k audio only' doesn't show up as a download option on any Youtube video. '128k audio only' shows up just like it used to. Just wondering what's going on. Thanks.

**Comment by inbasic** [comment]
I get 256K audio-only just fine. Send me a video link

**Comment by bobn42855** [comment]
Well ... this morning I'm getting 256k audio-only just fine as well. Sorry to have bothered you. Thanks for the quick response.
