### ISSUE TITLE
Automatically deletes video file?

### ISSUE THREAD

**Issue by saueressen** [inbasic/iaextractor#78]
Trying to download highest quality audio-only and video (with audio) available (so two download files).  The add-on downloads both, then always deletes the video and replaces it with the audio.   Do you know why?

**Comment by saueressen** [comment]
ahh, "ffmpeg exits with error code 256" message, maybe has something to do with it?  Using Ubuntu 12.04 LTS.   I'd like to end up with two files:  the highest quality audio file, and a 720p video file w/embedded audio.  What should my settings look like to accomplish this?

**Comment by inbasic** [comment]
Go to the settings and uncheck "Delete DASH files after combining them" to prevent the extension to delete downloaded files.

Does the final file has "- DASH" in the file name?

**Comment by saueressen** [comment]
no, it doesn't -- just one file, the DASH file gets deleted even when I
uncheck the "Delete DASH files" option.  I found a workaround:  I just
download the highest quality combined video and then the highest quality
audio only separately :)

It's still a very useful tool, once I get the hang of it...thank you!  Let
me know if you need any other info, otherwise, I appreciate the work you
put into it.  And it looks really nice, too :P

Saueressen*: Farm-fresh fermented foods*
Facebook.com/saueressen
Saueressen.com
(503) 260 9689

**Comment by inbasic** [comment]
Let me know if you still see this issue
