### ISSUE TITLE
Youtube to M4A comes to double the length of original file

### ISSUE THREAD

**Issue by miladam** [inbasic/iaextractor#79]
I'm having some issues lately, ever since I upgraded Firefox. Any clip that I convert to M4A for example, once opened in VLC shows a duration exactly double that of the original clip and I'm not able to access later parts of the download. It acts as if the download isn't complete and it's mute.

**Comment by inbasic** [comment]
Okay, so first uncheck "Delete DASH files after successful conversion" in the settings so that the extension keep the original file. Now see what is the length of the original file in your VLC player. If the length is okay, then there must be something wrong with your FFmpeg executable. What is your OS?

**Comment by miladam** [comment]
Thanks for the prompt reply, I'll try that. I'm on a Windows 7 platform running Firefox. 
On Sat, Mar 14, 2015 at 12:15 PM, InBasic <notifications@github.com> wrote:Okay, so first uncheck "Delete DASH files after successful conversion" in the settings so that the extension keep the original file. Now see what is the length of the original file in your VLC player. If the length is okay, then there must be something wrong with your FFmpeg executable. What is your OS?

**Comment by miladam** [comment]
so I think the problem was with the FFMPEG extension. The Dash file wouldn't load properly in VLC, where it would have double the time. I press the "install FFMPEG" button at the bottom but it didn't help. Instead I extracted FFMPEG in my C: drive locally and changed the address to the bin/FFMPEG.exe there and viola, all is good. I feel like there might be something wrong with the FFMPEG installation.
Thanks again either way, awesome product!
 


     On Saturday, March 14, 2015 1:03 PM, Milad AM <milad_am@yahoo.com> wrote:
   

 Thanks for the prompt reply, I'll try that. I'm on a Windows 7 platform running Firefox. 
On Sat, Mar 14, 2015 at 12:15 PM, InBasic <notifications@github.com> wrote:

Okay, so first uncheck "Delete DASH files after successful conversion" in the settings so that the extension keep the original file. Now see what is the length of the original file in your VLC player. If the length is okay, then there must be something wrong with your FFmpeg executable. What is your OS?—

**Comment by inbasic** [comment]
Great and thanks for sharing the solution.
