### ISSUE TITLE
How to set an external Download manager for this to use

### ISSUE THREAD

**Issue by TechKen1** [inbasic/iaextractor#80]
Is there some way to configure this package so it automatically uses an external download manager every time?  I don't seem to be finding anything on the settings pages for it to do this, and I would prefer to use my "DTA" and "FlashGot" managers, rather than the stupid, slow, irritating built in downloader in Firefox.

Other than this little issue, and the occasional speedbump when it's re-assembling a movie from the mp4 and m4a files, I just LOVE this thing!

**Comment by inbasic** [comment]
Not really and the reason is the integration with external download managers is not perfect, meaning the audio and video files are not being combined after both are downloaded. That is the reason why there is no such an option
