### ISSUE TITLE
Constant CPU usage

### ISSUE THREAD

**Issue by oscarfv** [inbasic/iaextractor#82]
With this extension installed FF constantly uses ~3% CPU when idle, with no tabs visiting YouTube (nor any other site with embedded videos.) After disabling the extension FF goes to 0% CPU.

Extension version: 0.4.3
FF: 37.0.1 on Kubuntu Linux 14.10 (64 bits)

**Comment by inbasic** [comment]
Would you please confirm the problem on a clean profile,
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by oscarfv** [comment]
After creating a new profile and installing Youtube Video and Audio Downloader, with only one tab showing the Firefox start page, CPU is at ~3%.

**Comment by inbasic** [comment]
I have no idea how it could be possible for YVAD to use CPU at all. It does absolutely noting when a YouTube page is not open.

Have you tried another restartless extension on a clean profile? YVAD is based on addon-sdk and this might be SDK's bug not YVAD's bug. For instance try my https://addons.mozilla.org/en-US/firefox/addon/gmail-notifier-restartless/ extension on a clean profile and see if you get the same CPU usage for this extension as well.

**Comment by oscarfv** [comment]
The other extension you mention does not cause the CPU activity while
idle.

By simply enabling/disabling YVAD I can start/stop the FF CPU activity.

**Comment by inbasic** [comment]
I have no idea why it consumes CPU when it is inactive. I'll keep this open for now. Please let me know if you have further info.
You can also try the latest beta version of the extension,
https://addons.mozilla.org/en-US/firefox/addon/youtube-video-and-audio-dow/versions
