### ISSUE TITLE
skipped itgas from dashmpd

### ISSUE THREAD

**Issue by arcm111** [inbasic/iaextractor#83]
The regex in `findOtherItags` function doesn't work when the `s` signature parameter is at the end of the url and not followed by a `/`.

you might want to change it from:
```javascript
var matchSig = (/\/s\/([a-zA-Z0-9\.]+)\//i.exec(dashmpd) || [null, null])[1];
```
to:
```javascript
var matchSig = (/\/s\/([a-zA-Z0-9\.]+)\/?/i.exec(dashmpd) || [null, null])[1];
```
note the aditional `?` to find zero or one match of `/`.

**Comment by inbasic** [comment]
fixed, thanks for the report.
https://addons.mozilla.org/firefox/downloads/file/310746/youtube_video_and_audio_downloader-0.4.4b2-fx.xpi?src=devhub
