### ISSUE TITLE
JSon Parse Syntax Error

### ISSUE THREAD

**Issue by haveanicedave** [inbasic/iaextractor#84]
I have updated both Firefox and your plugin, and I am now getting errors when just trying to access the links menu.

Showing JSon Parse errors. 

Saying that this is an error on certain lines. I have attached the screenshot.
![json_parse_error_downloader_plugin](https://cloud.githubusercontent.com/assets/12128732/7339905/953f1e3e-ec33-11e4-900f-5c645730255e.jpg)

**Comment by haveanicedave** [comment]
Also, for the record it's the latest version of firefox 37.0.2 as well as the latest version of the plugin.

**Comment by haveanicedave** [comment]
Also, just noticed it seems that this error is happening on some pages but not others.

This error happened here: https://www.youtube.com/watch?v=7tHGojrbaA8

but did not happen here: https://www.youtube.com/watch?v=c85w_9A_6c8

**Comment by Xenopathic** [comment]
@haveanicedave For a quick fix, set the preference `extensions.feca4b87-3be4-43da-a1b1-137c24220968@jetpack.ccode` to `["r","r"]` in `about:config` (you'll need to create a new string preference). Looks like the problem exists at https://github.com/inbasic/iaextractor/blob/beta/src/lib/youtube.js#L492 as a result of 83ec06e73bae3ee2e259c373d9ebcf11e2c31b9e

**Comment by inbasic** [comment]
@haveanicedave What was the value of `ccode` before changing it?

**Comment by haveanicedave** [comment]
I haven't changed anything.I'm not entirely sure what you are referencing. I am in the options for the plugin, however I do not see a place to "set the preference extensions". 
 


     On Monday, April 27, 2015 10:37 PM, InBasic <notifications@github.com> wrote:
   

 @haveanicedave What was the value of ccode before changing it?—

**Comment by inbasic** [comment]
In a new tab, load "about:config". Search for `jetpack.ccode` on the searchbox and let me know the value of `jetpack.ccode` as well as `jetpack.player`

**Comment by haveanicedave** [comment]
Actually, I do not even see those files there. 

Here is my version info: 
extensions.feca4b87-3be4-43da-a1b1-137c24220968@jetpack.version;0.4.4

Should I add those files somehow?
 


     On Monday, April 27, 2015 11:06 PM, InBasic <notifications@github.com> wrote:
   

 In a new tab, load "about:config". Search for jetpack.ccode on the searchbox and let me know the value of jetpack.ccode as well as jetpack.player—

**Comment by DeltaN9ne** [comment]
I have this same error and also missing both jetpack.ccode and jetpack.player in about:config

**Comment by inbasic** [comment]
please confirm the problem on a clean profile,
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by inbasic** [comment]
also what is your Firefox version?

**Comment by DeltaN9ne** [comment]
Created a new profile and even uninstalled/reinstalled firefox and still have the same error, my version is 37.0.2 (latest).

**Comment by haveanicedave** [comment]
i "refreshed firefox profile" and mine seems like all jetpack references. I guess I will have to reinstall ffd
 


     On Monday, April 27, 2015 11:54 PM, DeltaN9ne <notifications@github.com> wrote:
   

 Created a new profile and even uninstalled/reinstalled firefox and still have the same error, my version is 37.0.2 (latest).—

**Comment by inbasic** [comment]
Okay then in the new  profile, close all windows, now open a single window and then open Error console (Ctrl+Shift+J) and see if you get any error in the console when you initiate Firefox. You can take an screenshot and drop it here to share.

**Comment by haveanicedave** [comment]
Here it is attached. I installed the latest version of ffd again as well before I took this screenshot
![downloader_error](https://cloud.githubusercontent.com/assets/12128732/7364490/0f0d5916-ed3c-11e4-9309-3719272130f6.jpg)

**Comment by inbasic** [comment]
Is this fixed,
https://addons.mozilla.org/en-US/firefox/addon/youtube-video-and-audio-dow/versions/

**Comment by DeltaN9ne** [comment]
Yes it is working now, Thank you!

**Comment by haveanicedave** [comment]
Yup..working!

**Comment by inbasic** [comment]
Great!
