### ISSUE TITLE
Is there anyway to download 60fps DASH from YouTube...

### ISSUE THREAD

**Issue by bobcat1656** [inbasic/iaextractor#86]
Hi! This message is in regards to the YouTube Video and Audio Downloader Firefox extension. This is the forum that was stated to request support. I love your product and works well for other types of video. However, YouTube has begun allowing 60FPS files for 720p and 1080p files. From what I understand, they are also DASH videos the same as 480p and 1080p. Is there anyway to add support for these files?

Thank you in advance!

**Comment by inbasic** [comment]
Yes it is possible, in the injected menu, usually on page 2,  there are some items with 60fps icon (only if available).

**Comment by bobcat1656** [comment]
Awesome! I took a look and see it now. It kinda confused me as it wasn't on the first page nor is there an option to automatically mux it(At least as far as I can find). But I can live with that. Thank you again! If I can figure out how to close this ticket I will do so otherwise you may close it. ^.^

**Comment by inbasic** [comment]
> ... there an option to automatically mux it ...

Just click on the a 60fps item in the injected menu. If you have FFmpeg installed, a proper audio will be selected and when both are downloaded, they will be combined together.

**Comment by inbasic** [comment]
Also you can combine them using https://addons.mozilla.org/en-US/firefox/addon/media-converter-and-muxer/ as well.
