### ISSUE TITLE
Error cant detect url encoded...

### ISSUE THREAD

**Issue by rivon3** [inbasic/iaextractor#88]
Basicly the video have age restriction and i cant download it.  i sign in and can watch it but cant use this prog to download the video. How to make thing work?

**Comment by inbasic** [comment]
Are you sure you are not logged-in in the private window?

**Comment by rivon3** [comment]
Private window? I'm a bit confused
I basically tried to download video without signing in my Google account and error pop out.
Then i sign in my google account and tried download video again but got the same error 
May be i just dont know something?

**Comment by inbasic** [comment]
Well, as far as I know if you are logged in into your Google account and are able to watch the video, the extension should be able to download it considering you are not in the private mode, https://support.mozilla.org/en-US/kb/private-browsing-use-firefox-without-history

**Comment by rivon3** [comment]
To activate this mode, as explained on that page, you need to specifically chose to use it and i was not even aware this option existed...
 Im not in the private mode for sure. I use addblocker i tried to desable it but its not the case.
The video in question http://www.youtube.com/watch?t=19&v=1-l29HlKkXU

**Comment by rivon3** [comment]
You were right.
In options it was set to disable history and this interfere with downloading age restricted videos.
 Thank you.

**Comment by inbasic** [comment]
Great!
