### ISSUE TITLE
Add-On 'captures' new tab shortcut

### ISSUE THREAD

**Issue by Daniel-Krebs** [inbasic/iaextractor#91]
Version 0.4.4.1.1 on Linux Mint 17.1 x64 with FF 38.0
 CTRL + T opens a new tab with the youtube startpage instead of an empty tab as before.  Removing the shortcut for "download video files using keyboard shortcut" solves this problem. I think such a standard shortcut should not be replaced/modified by default.

**Comment by inbasic** [comment]
The default shortcut is `Accel + Shift + Q`. I am not sure why `CTRL + T` has been set for you
https://github.com/inbasic/iaextractor/blob/master/src/package.json#L107-L111

Can you confirm on a clean profile? https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by Daniel-Krebs** [comment]
Sorry for the late replay. I retried with a clean profile using a portable version of FF and had no issues, the shortcut then was Accel + Shift + Q, as you said. Maybe it was a conflict with other plugins? Anyway, I'm glad this wasn't default behaviour and I could change it via settings. 
Thanks for taking time!
