### ISSUE TITLE
Need to refresh page to see Download button.

### ISSUE THREAD

**Issue by SlimF** [inbasic/iaextractor#92]
Since 1 or 2 days ago I noticed that every time I start a new video, the Download button is missing until I refresh the page. I'm using latest FF version on Windows 10, I tried to reinstall the addon and tried with a new profile too but no luck. A friend has the same problem on W7 too.

**Comment by inbasic** [comment]
Please try the addon on a clean profile, https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by SlimF** [comment]
I tried with a new profile but the problem persists. :/

**Comment by inbasic** [comment]
okay, please open the Error Console (Ctrl + Shift + J), clear it and open a YouTube page. Is there any new relevant error in the console?

**Comment by SlimF** [comment]
http://pastebin.com/J55DeH2r and after a refresh http://pastebin.com/GiYjZ4st

**Comment by jdgalt** [comment]
I see this problem too.

**Comment by lsimpson50** [comment]
This problem just started for me too.  Firefox 38.0.5, Windows 7.

**Comment by Nilknarf2015** [comment]
This same issue just started for me right after updating to Firefox 38.0.5. I made sure I have the latest version of the addon. I'm on Win 7 64 bit.

**Comment by tedparkes** [comment]
Same issue, Firefox 38.0.5, dont even see the top right download button, nevermind one on the page, it looks like the addon is not installed at all.

**Comment by tedparkes** [comment]
Updating to Firefox 39 has resolved the issue.

**Comment by lsimpson50** [comment]
Updating to Firefox 39 did not solve the issue for me.  The problem is the same with 39.

**Comment by 98se** [comment]
When Greasemonkey is installed, it was settled.
I don't understand the reason, but you'd be able to bypass this issue.

**Comment by inbasic** [comment]
The issue is fixed on the latest built,
https://addons.mozilla.org/en-US/firefox/addon/youtube-video-and-audio-dow/versions/0.4.5

Thanks for the report.
