### ISSUE TITLE
Not available for Firefox 26.0HTTcryPt/Add-on

### ISSUE THREAD

**Issue by Californio** [inbasic/iaextractor#94]
the addon is no longer active.   Apparently due to an encrypting app HTTcyPT 
viewing my list of AddOns  this app was disabled (Greyed out) and the msg displayed 
"Not available for Firefox 26.0HTTcryPt/Add-on"   I removed the HTTcryPt, rebooted, and now this app appears to be active again in THE LIST of addons but the download button doesn't appear anymore.

going to this page for updates 
https://addons.mozilla.org/en-US/firefox/addon/youtube-video-and-audio-dow/?src=api
the same msg shows under the "ADD to Firefox" button  (see image)
![yt dloader not available](https://cloud.githubusercontent.com/assets/13344073/8691078/bc1c27d6-2a72-11e5-9605-9439a71fc912.png)

However, I had been using firefox 38.01 not FFX 26.0 and the app had been working up until FFX 39.0 came out.   (I updated to 38.05 and updated Adobe flash to latest but  your app  No longer works (but the list of Addons says it's active)

**Comment by inbasic** [comment]
The addon only works with FF greater version > 29.0
