### ISSUE TITLE
FFmpeg converter existed with error code -1

### ISSUE THREAD

**Issue by iFrancie** [inbasic/iaextractor#96]
Hi , I'm using the "YouTube video and audio dowloader"Addon with the FFmpeg to dowload the 1080p videos on YouTube ,and dowloading succeed ,But that notification appears .
Can you tell me what does this mean ? Please ?
I've already installed the FFmpeg .
![ffmpeg](https://cloud.githubusercontent.com/assets/13374449/8739692/670a911e-2c71-11e5-8ba0-f31293c316b9.PNG)

**Comment by inbasic** [comment]
you have downloaded FFmpeg's source code. You need the executable file,
Head to https://www.ffmpeg.org/download.html and from "Get the packages" section download the executable

**Comment by iFrancie** [comment]
Thank you so much ! But would you tell me how to make it combine the "DASH.m4a" and "DASH.mp4" automatically ?
Thanks again .

**Comment by inbasic** [comment]
You dont need to do much. Just download the FFmpeg executable. Go to the options and point the extension to use the executable. Now when even you download a 'vidoe-only' item from the injected menu, the extension downloads an 'audio-only' stream as well an combines them together.

**Comment by inbasic** [comment]
if you have local files you want to combine them, you can use my https://addons.mozilla.org/en-US/firefox/addon/media-converter-and-muxer/ extension

**Comment by iFrancie** [comment]
Thanks a million ,it works !
