### ISSUE TITLE
After downloading, V/A Downloader won't "let go" and turn off - having to disable/enable in Firefox_Extensions tab

### ISSUE THREAD

**Issue by BrianHath777** [inbasic/iaextractor#98]
I have a feeling this might just be my install, since I think someone would have complained by now?  Anyway, I download the 128kps (ugh!) for an AAC that YouTube has now restricted us to, and notice I can't download another file because YouTube Video and Audio Downloader is still "busy" downloading the previous file, according to the tab/button at the top of the Firefox window, nor will clicking the "X" to cancel it do anything.  I am disabling then enabling via the Tools/Extensions window in Firefox to get this add-on to 'stop it!'   :-)  What is going on?

**Comment by inbasic** [comment]
For some reason, the download manager API is not responding. You need to close your Firefox and reopen it

**Comment by BrianHath777** [comment]
Oh, I've already tried that. I've removed the extension, downloaded it fresh, reinstalled it, same thing happens.  Is my install of Firefox "destroyed" - do I need to remove it and start all over?

**Comment by inbasic** [comment]
So an unresponsive download is in the YVAD's download tab even when you restart your Firefox?

**Comment by BrianHath777** [comment]
Yup.  Or when I disable/enable it via the Firefox Tools/Add-ons/Extensions tab.  Plus, it normally just goes back to normal when a download is finished - never seen this happen before.  Mac OS X 10.6.8 & Firefox 39.0

**Comment by inbasic** [comment]
do you still have this issue?
