### ISSUE TITLE
went back to v4.4.1.1 with auto-update set to OFF and fixed my problem AND 256 AAC is back!!

### ISSUE THREAD

**Issue by BrianHath777** [inbasic/iaextractor#99]
So I am staying put at this version.  Firefox 39.0.  Mac OS X 10.6.8

**Comment by miladam** [comment]
Perfect fix, I was going reinstalling FFMPEG thinking that was the issue. Thanks for posting this.

**Comment by BrianHath777** [comment]
Oh, I went to the Firefox/Tools/Add-ons/prefs for the YouTube V&A DL'r and removed/reinstalled ffmpeg on a hunch, and that fixed my problem with the API not "letting go" after downloads - so - everything is ok now - I got the 256 AAC's back by going back to the previous version, and got rid of the 'hang' on the download panel by removing/re-installing the ffmpeg converter.  That part must have been my install being corrupted.

**Comment by elisabethmarina3** [comment]
Best apps for all small and large business. To mobilized, boost up your business and attract new customers.We have applications for Business Solution, Educational app, E-Commerce app, Medical app and more. Your apps will be uploading at Amazon, Apple and Google app store

**Comment by inbasic** [comment]
This issue is fixed on the latest release
